package by.epam.pretraining.task2;

public class Main {

    public static void main(String[] args) {

        System.out.println("One-dimensional arrays:");
//        System.out.print("Task 1.1: ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise1.run();
//        System.out.println("Task 1.2: ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise2.run();
//        System.out.println("Task 1.3: ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise3.run();
//        System.out.println("Task 1.4 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise4.run();
//        System.out.println("Task 1.5 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise5.run();
//        System.out.println("Task 1.6 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise6.run();
//        System.out.println("Task 1.7 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise7.run();
//        System.out.println("Task 1.8 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise8.run();
//        System.out.println("Task 1.9 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise9.run();
//        System.out.println("Task 1.10 ");
//        by.epam.pretraining.task2.one_dimensional_array.exercise10.run();

        System.out.println("Multidimensional arrays:");
//        System.out.println("Task 2.1 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise1.run();
//        System.out.println("Task 2.2 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise2.run();
//        System.out.println("Task 2.3 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise3.run();
//        System.out.println("Task 2.4 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise4.run();
//        System.out.println("Task 2.5 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise5.run();
//        System.out.println("Task 2.6 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise6.run();
//        System.out.println("Task 2.7 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise7.run();
//        System.out.println("Task 2.8 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise8.run();
//        System.out.println("Task 2.9 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise9.run();
//        System.out.println("Task 2.10 ");
//        by.epam.pretraining.task2.multidimensional_array.exercise10.run();
//        System.out.println("Task 2.11 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise11.run();
//        System.out.println("Task 2.12 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise12.run();
//        System.out.println("Task 2.13 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise13.run();
//        System.out.println("Task 2.14 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise14.run();
//        System.out.println("Task 2.15 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise15.run();
//        System.out.println("Task 2.16 ");
//        by.epam.pretraining.task2.multidimensional_array.Exercise16.run();

        System.out.println("Sorting of one-dimensional arrays:");
//        System.out.println("Task 3.1 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise1.run();
//        System.out.println("Task 3.2 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise2.run();
//        System.out.println("Task 3.3 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise3.run();
//        System.out.println("Task 3.4 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise4.run();
//        System.out.println("Task 3.5 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise5.run();
//        System.out.println("Task 3.6 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise6.run();
//        System.out.println("Task 3.7 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise7.run();
//        System.out.println("Task 3.8 ");
//        by.epam.pretraining.task2.sorting_of_one_dimensional_array.Exercise8.run();

        System.out.println("Decomposition using methods:");
//        System.out.println("Task 4.1 ");
//        by.epam.pretraining.task2.decomposition.Exercise1.run();
//        System.out.println("Task 4.2 ");
//        by.epam.pretraining.task2.decomposition.Exercise2.run();
//        System.out.println("Task 4.3 ");
//        by.epam.pretraining.task2.decomposition.Exercise3.run();
//        System.out.println("Task 4.4 ");
//        by.epam.pretraining.task2.decomposition.Exercise4.run();
//        System.out.println("Task 4.5 ");
//        by.epam.pretraining.task2.decomposition.Exercise5.run();
//        System.out.println("Task 4.6 ");
//        by.epam.pretraining.task2.decomposition.Exercise6.run();
//        System.out.println("Task 4.7 ");
//        by.epam.pretraining.task2.decomposition.Exercise7.run();
//        System.out.println("Task 4.8 ");
//        by.epam.pretraining.task2.decomposition.Exercise8.run();
//        System.out.println("Task 4.9 ");
//        by.epam.pretraining.task2.decomposition.Exercise9.run();
//        System.out.println("Task 4.10 ");
//        by.epam.pretraining.task2.decomposition.Exercise10.run();
//        System.out.println("Task 4.11 ");
//        by.epam.pretraining.task2.decomposition.Exercise11.run();
//        System.out.println("Task 4.12 ");
//        by.epam.pretraining.task2.decomposition.Exercise12.run();
//        System.out.println("Task 4.13");
//        by.epam.pretraining.task2.decomposition.Exercise13.run();
//        System.out.println("Task 4.14");
//        by.epam.pretraining.task2.decomposition.Exercise14.run();
//        System.out.println("Task 4.15");
//        by.epam.pretraining.task2.decomposition.Exercise15.run();
//        System.out.println("Task 4.16");
//        by.epam.pretraining.task2.decomposition.Exercise16.run();
//        System.out.println("Task 4.17");
//        by.epam.pretraining.task2.decomposition.Exercise17.run();
    }
}
